import { execFile } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { promisify } from 'node:util';
import { renderTrackingPlan, type SeamMap, type TrackingPlan } from '@toqar/registry';
import { z } from 'zod';
import type { ModelSession } from './model.js';

const run = promisify(execFile);

/** One insertion the model proposes; validated before it touches disk. */
const editSchema = z.object({
  file: z.string().min(1),
  afterLine: z.number().int().nonnegative(),
  insert: z.string().min(1),
});
const editsSchema = z.array(editSchema).max(50);
export type ProposedEdit = z.infer<typeof editSchema>;

export interface HostCheck {
  command: string;
  args: string[];
}

export interface ImplementOptions {
  repoPath: string;
  plan: TrackingPlan;
  seamMap: SeamMap;
  /** The host repo's own verification commands — all must pass. */
  hostChecks: HostCheck[];
  /** Optional model pass proposing additional insertions. */
  session?: ModelSession;
}

export type ImplementResult =
  | {
      status: 'implemented';
      filesWritten: string[];
      editsApplied: ProposedEdit[];
      rejectedEdits: { edit: unknown; reason: string }[];
    }
  | { status: 'verification_failed'; failedCheck: string; output: string };

/* ---- wrapper generation: typed emitters only for planned events ---- */

const EMITTERS: Record<string, string> = {
  task_started: `  taskStarted: (
    ctx: TaskContext,
    p: { initiator: 'human' | 'agent' | 'schedule' | 'api'; input_ref?: string },
  ) => track('task_started', ctx, p),`,
  task_completed: `  taskCompleted: (
    ctx: TaskContext,
    p: {
      verification: 'verified' | 'self_reported';
      verifier?: string;
      duration_ms: number;
      steps_total: number;
      cost_usd?: number;
      output_ref?: string;
    },
  ) => track('task_completed', ctx, p),`,
  task_failed: `  taskFailed: (
    ctx: TaskContext,
    p: { error: { type: string; message?: string }; retryable: boolean; duration_ms: number },
  ) => track('task_failed', ctx, p),`,
  task_abandoned: `  taskAbandoned: (
    ctx: TaskContext,
    p: { abandoned_by: 'human' | 'timeout' | 'system'; reason?: string; duration_ms: number },
  ) => track('task_abandoned', ctx, p),`,
  step_executed: `  stepExecuted: (
    ctx: TaskContext,
    p: {
      step_id: string;
      step_index: number;
      step_type: 'llm_call' | 'tool_call' | 'retrieval' | 'code_execution' | 'handoff' | 'other';
      tool_name?: string;
      model?: string;
      latency_ms: number;
      status: 'ok' | 'error' | 'timeout';
    },
  ) => track('step_executed', ctx, p),`,
  handoff_to_human: `  handoffToHuman: (
    ctx: TaskContext,
    p: { handoff_id: string; reason: 'approval_required' | 'low_confidence' | 'error' | 'policy' | 'clarification' | 'user_request'; blocking: boolean },
  ) => track('handoff_to_human', ctx, p),`,
  human_approved: `  humanApproved: (
    ctx: TaskContext,
    p: { handoff_id: string; response_latency_ms: number },
  ) => track('human_approved', ctx, p),`,
  human_edited: `  humanEdited: (
    ctx: TaskContext,
    p: { handoff_id?: string; artifact_type: string; edit_magnitude?: { unit: 'chars' | 'tokens' | 'lines'; value: number } },
  ) => track('human_edited', ctx, p),`,
  human_overrode: `  humanOverrode: (
    ctx: TaskContext,
    p: { handoff_id?: string; takeover_step_id?: string; reason?: string },
  ) => track('human_overrode', ctx, p),`,
  feedback_given: `  feedbackGiven: (
    ctx: TaskContext,
    p: { rating: { kind: 'binary' | 'scale'; value: number }; source: 'end_user' | 'operator'; comment_ref?: string },
  ) => track('feedback_given', ctx, p),`,
};

function wrapperSource(events: string[]): string {
  const emitters = events
    .filter((e) => e in EMITTERS)
    .map((e) => EMITTERS[e])
    .join('\n\n');
  return `/**
 * TOQAR analytics wrapper — generated by the instrumentation agent from
 * the approved tracking plan in analytics/tracking-plan.md.
 * Fire-and-forget: analytics can never block or crash the agent loop.
 */

type Destination = { capture: (event: string, props: object) => void };

function makeDestination(): Destination {
  if (process.env.ANALYTICS_DISABLED === '1') {
    return { capture: () => {} };
  }
  // Wire the engagement's destination (PostHog key or Toqar collector).
  return { capture: () => {} };
}

const destination = makeDestination();

export interface TaskContext {
  task_id: string;
  run_id: string;
  task_type: string;
  session_id?: string;
}

const AGENT = {
  name: process.env.TOQAR_AGENT_NAME ?? 'agent',
  version: process.env.RELEASE_SHA,
};

function track(event: string, ctx: TaskContext, props: object): void {
  try {
    destination.capture(event, {
      event_id: crypto.randomUUID(),
      schema_version: '0.1.0',
      timestamp: new Date().toISOString(),
      agent: AGENT,
      ...ctx,
      ...props,
    });
  } catch (err) {
    console.warn('[analytics] drop:', event, err);
  }
}

export const analytics = {
${emitters}
};
`;
}

/* ---- deterministic wiring ---- */

const EXPORTED_ASYNC_FN = /^export (?:default )?async function (\w+)\(\s*(\w+)?/;

function camelToSnake(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}

interface FileEdits {
  [file: string]: { afterLine: number; insert: string }[];
}

async function applyFileEdits(repoPath: string, edits: FileEdits): Promise<void> {
  for (const [file, inserts] of Object.entries(edits)) {
    const path = join(repoPath, file);
    const lines = (await readFile(path, 'utf8')).split('\n');
    for (const { afterLine, insert } of [...inserts].sort((a, b) => b.afterLine - a.afterLine)) {
      lines.splice(afterLine, 0, insert);
    }
    await writeFile(path, lines.join('\n'));
  }
}

export async function implementPlan(opts: ImplementOptions): Promise<ImplementResult> {
  const { repoPath, plan, seamMap } = opts;
  const filesWritten: string[] = [];

  // 1. The reviewable plan document.
  await mkdir(join(repoPath, 'analytics'), { recursive: true });
  await writeFile(join(repoPath, 'analytics/tracking-plan.md'), renderTrackingPlan(plan));
  filesWritten.push('analytics/tracking-plan.md');

  // 2. The wrapper, with emitters only for planned events.
  const events = [...plan.modified, ...plan.added].map((e) => e.event);
  await mkdir(join(repoPath, 'src'), { recursive: true });
  await writeFile(join(repoPath, 'src/analytics.ts'), wrapperSource(events));
  filesWritten.push('src/analytics.ts');

  // 3. Deterministic wiring: task_started emission at every task_start seam.
  const wiring: FileEdits = {};
  for (const seam of seamMap.seams.filter((s) => s.kind === 'task_start')) {
    const [file, lineStr] = seam.location.split(':');
    if (!file || !lineStr) continue;
    const lineNo = Number(lineStr);
    const source = await readFile(join(repoPath, file), 'utf8');
    const lines = source.split('\n');
    const fnLine = lines[lineNo - 1] ?? '';
    const match = EXPORTED_ASYNC_FN.exec(fnLine);
    if (!match?.[1]) continue;
    const taskType = camelToSnake(match[1]);
    const idExpr = match[2] ? `String(${match[2]})` : 'crypto.randomUUID()';
    const importPath = relative(dirname(file), 'src/analytics').replace(/\\/g, '/');
    const importLine = `import { analytics } from '${importPath.startsWith('.') ? importPath : `./${importPath}`}.js';`;

    wiring[file] ??= [];
    if (!source.includes(importLine)) {
      const lastImport = lines.reduce((acc, l, i) => (l.startsWith('import ') ? i + 1 : acc), 0);
      wiring[file].push({ afterLine: lastImport, insert: importLine });
    }
    const insertAt = lineNo + (wiring[file].some((w) => w.insert === importLine) && lineNo > 0 ? 1 : 0);
    wiring[file].push({
      afterLine: insertAt,
      insert: [
        `  const __toqarCtx = { task_id: ${idExpr}, run_id: crypto.randomUUID(), task_type: '${taskType}' };`,
        `  analytics.taskStarted(__toqarCtx, { initiator: 'api' });`,
      ].join('\n'),
    });
  }
  await applyFileEdits(repoPath, wiring);

  // 4. Model-proposed insertions, validated before touching disk.
  const editsApplied: ProposedEdit[] = [];
  const rejectedEdits: { edit: unknown; reason: string }[] = [];
  if (opts.session) {
    const response = await opts.session.send(
      [
        'Propose insertion edits wiring the remaining seams to the analytics wrapper.',
        'Respond ONLY with a JSON array of {"file","afterLine","insert"} objects.',
        `Seams: ${JSON.stringify(seamMap.seams)}`,
      ].join('\n'),
    );
    let proposed: unknown = [];
    try {
      const jsonText = /\[[\s\S]*\]/.exec(response.text)?.[0] ?? '[]';
      proposed = JSON.parse(jsonText);
    } catch {
      rejectedEdits.push({ edit: response.text.slice(0, 200), reason: 'unparseable response' });
    }
    const parsed = editsSchema.safeParse(proposed);
    const candidates = parsed.success ? parsed.data : [];
    const applicable: FileEdits = {};
    for (const edit of candidates) {
      const target = resolve(repoPath, edit.file);
      if (!target.startsWith(resolve(repoPath) + '/')) {
        rejectedEdits.push({ edit, reason: 'path escapes the repo' });
        continue;
      }
      try {
        await readFile(target, 'utf8');
      } catch {
        rejectedEdits.push({ edit, reason: 'file does not exist' });
        continue;
      }
      (applicable[edit.file] ??= []).push(edit);
      editsApplied.push(edit);
    }
    await applyFileEdits(repoPath, applicable);
  }

  // 5. The host repo's own verification — all green or no PR.
  for (const check of opts.hostChecks) {
    try {
      await run(check.command, check.args, { cwd: repoPath });
    } catch (err) {
      const e = err as { stderr?: string; stdout?: string; message?: string };
      return {
        status: 'verification_failed',
        failedCheck: `${check.command} ${check.args.join(' ')}`,
        output: (e.stderr || e.stdout || e.message || '').slice(0, 2000),
      };
    }
  }

  return { status: 'implemented', filesWritten, editsApplied, rejectedEdits };
}
